# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: Demo 1

variables:
  buildConfiguration: 'Release'

stages:
 - stage: 'Build'
   jobs:
   - job:
     steps:

     - task: Npm@1
       inputs:
        command: 'install'
        workingDir: 'ClientApp'
      
     - task: Npm@1
       inputs:
        command: 'ci'
        workingDir: 'ClientApp'
     
     - script: dotnet build --configuration $(buildConfiguration)
        displayName:'dotnet build $(buildConfiguration)'

     - task: DotNetCoreCLI@2
       inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration = $(buildconfiguration) --output $(build.artifactsstagingdirectory)/$'
        zipAfterPublish: true
     - task: PublishBuildArtifacts@1
       inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'